language: node_js

os:
 - linux
 - osx
 - windows

node_js:
  # TBD ISSUE with testing on Node.js 4
  # - 4
  - 6
  - 8
  - 10


matrix:
  # Test depending on Node.js version:
  # * need to use npm test on Node.js 6
  #   (yarn test seems to crash; yarn prepare-release not working)
  # * keep yarn test & yarn prepare-release on separate
  #   Node.js versions since they both take some time to run
  - node_js: 6
    env: TEST_COMMAND="npm test"
  - node_js: 8
    env: TEST_COMMAND="yarn test"
  - node_js: 10
    env: TEST_COMMAND="yarn prepare-release"

# Note that yarn is implictly installed due to existence of yarn.lock.

before_script:
  - node --version
  - npm --version
  - yarn --version

script:
  - yarn lint
  - $TEST_COMMAND
